# Generated by Django 3.0.8 on 2020-08-01 17:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='comment_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='likes_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 1, 23, 9, 33, 68992)),
        ),
        migrations.AddField(
            model_name='blog',
            name='read_duration',
            field=models.IntegerField(default=0),
        ),
    ]
