# Generated by Django 3.0.8 on 2020-08-01 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_auto_20200801_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('posts_count', models.IntegerField()),
            ],
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='comment_count',
            new_name='comments_count',
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 1, 23, 35, 26, 530913)),
        ),
    ]
