# Generated by Django 3.0.8 on 2020-08-03 01:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20200802_1807'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='share_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 8, 3, 7, 29, 23, 504154)),
        ),
    ]
