# Generated by Django 3.0.8 on 2020-09-05 06:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_auto_20200803_0744'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='meta_description',
            field=models.CharField(default='default description', max_length=300),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_tags',
            field=models.CharField(default='meta tags', max_length=500),
        ),
        migrations.AddField(
            model_name='blog',
            name='meta_title',
            field=models.CharField(default='default title', max_length=100),
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='blogs.Category'),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 5, 12, 6, 40, 217203)),
        ),
    ]
