# Generated by Django 3.0.8 on 2020-09-07 13:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0012_auto_20200906_0047'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 7, 18, 57, 9, 79516)),
        ),
        migrations.AddField(
            model_name='blog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 7, 18, 57, 9, 79516)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 7, 18, 57, 9, 79516)),
        ),
    ]
