# Generated by Django 3.0.8 on 2020-09-08 18:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0013_auto_20200907_1857'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='updated_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 23, 58, 59, 285503)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='created_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 23, 58, 59, 285503)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='deleted_on',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 23, 58, 59, 285503)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='publish_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 9, 8, 23, 58, 59, 285503)),
        ),
    ]
